[settings]
dotfiles.root = "dotfiles"
dotfiles.default_mode = "symlink"

[bootstrap.user]
login_shell = "/bin/zsh"

[bootstrap.packages]
"flatpak:be.alexandervanhee.gradia" = "latest"

[dotfiles]
"~/.zshrc" = "dotfiles/.zshrc"
"~/.zshenv" = "dotfiles/.zshenv"
"~/.alias.zsh" = "dotfiles/.alias.zsh"
"~/.p10k.zsh" = "dotfiles/.p10k.zsh"
"~/.gitconfig" = "dotfiles/.gitconfig"
"~/.config/git/ignore" = "dotfiles/.config/git/ignore"
"~/.config/ghostty/config" = "dotfiles/.config/ghostty/config"
"~/.config/mise/config.toml" = "dotfiles/.config/mise/config.toml"
"~/.config/environment.d/flatpak.conf" = "dotfiles/.config/environment.d/flatpak.conf"
"~/.config/JetBrains/IntelliJIdea/idea64.vmoptions" = "dotfiles/.config/JetBrains/IntelliJIdea/idea64.vmoptions"
"~/.config/user-dirs.dirs" = "dotfiles/.config/user-dirs.dirs"
"~/.config/user-dirs.locale" = "dotfiles/.config/user-dirs.locale"
"~/.local/bin/gradia" = "dotfiles/.local/bin/gradia"
