icons_format = "{icon}"

[theme]
theme = "srcery"
[theme.overrides]
idle_bg = "#323232"
idle_fg = "#ffffff"
good_fg = { link = "idle_fg" }
good_bg = { link = "idle_bg" }
warning_fg = { link = "idle_fg" }
warning_bg = { link = "idle_bg" }
info_bg = { link = "idle_bg"}
# alternating_tint_bg = { link = "idle_bg"}
separator =  "  " #"｜"
separator_fg = { link = "idle_fg" }

[icons]
icons = "awesome4"

[[block]]
block = "music"
# format = " $play  $next {$combo.str(max_w:35) |}"
player = "spotify"
[block.theme_overrides]
info_fg = { link = "idle_fg" }
info_bg = { link = "idle_bg" }

[[block]]
block = "battery"
format = " $icon $percentage "

[[block]]
block = "cpu"
format = " $icon "

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $available.eng(w:2) "

[[block]]
block = "docker"
interval = 2
format = " $icon { $running/$total |}"

[[block]]
block = "keyboard_layout"
driver = "sway"
[[block.click]]
button="left"
cmd="swaymsg input type:keyboard xkb_switch_layout next"

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 1
format = " $timestamp.datetime(f:'%Y-%m-%d %T') "
[[block.click]]
button = "left"
cmd = "date '+%Y-%m-%d %H:%M' | wl-copy"
