theme = "native"
icons = "awesome"
incons_format = " <span font_family='Leberation Mono'>{icon}</span> "

[[block]]
block = "music"
# player = "spotify"
marquee = false
dynamic_width = true
max_width = 45
hide_when_empty = true
format = "{title}"

[[block]]
block = "networkmanager"
on_click = "alacritty -e nmtui"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
interface_name_include = []
device_format = "{icon}{ap}"
ap_format = "{ssid} {strength}"

[[block]]
block = "docker"
interval = 2
format = "{running}/{total}"

[[block]]
block = "battery"
interval = 10
format = "{percentage}"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "memory"
format_mem = "{mem_free;M}"
format_swap = "{swap_free;M}"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"
on_click = "pavucontrol"

[[block]]
block = "time"
interval = 1
# on_click = "date '+%Y-%m-%d %H:%M' | wl-copy"
format = "%Y-%m-%d %T"
